---
- name: Install apache
  yum:
    name: httpd
    state: latest

- name: Copy index.html
  copy:
    src: index.html
    dest: /var/www/html
    owner: root
    group: apache
    mode: '0644'
# Enable and start service httpd 
  notify:
    - enable httpd
    - start httpd

- name: Include task to open port
  include_tasks: open_firewalld_ports.yml
