---
- name: install Apache and open ports
  hosts: node1.example.com

  vars:
    html_path: /var/www/html/index.html

  tasks:
  - name: Install apache
    yum:
      name: httpd
      state: latest

  - name: Create html
    shell: |
      echo "Welcome to my web server" > "{{ html_path }}"

  - name: Start apache
    service:
      name: httpd
      enabled: yes
      state: started

  - name: Check status
    shell: "systemctl status httpd"

  - name: Open port
    firewalld:
      port: 80/tcp
      permanent: yes
      immediate: yes
      state: enabled
